print("Период развития человека, 18-8 млн. лет назад -")
period1 = input()
print("Период развития человека, около 5 млн. лет назад -")
period2 = input()
print("Период развития человека, 2 млн. - 500 тыс. лет назад -")
period3 = input()
print("Период развития человека, 500 - 30 тыс. лет назад -")
period4 = input()
print("Период развития человека, 40 тыс. лет назад -")
period5 = input()
print("Период развития человека, 10 тыс. лет назад -")
period6 = input()
print(period1, period2, period3, period4, period5, period6, sep = " => ")