print("Вид вашего животного - ")
kind_an = input()
print("Возраст вашего животного")
age = input()
print("Как зовут вашего питомца? ")
name = input()
print("Это", kind_an, "по кличке", name+'.', "Его возраст", age)